Name:           perl-App-Dapper
Version:        0.18
Release:        3%{?dist}
Summary:        Publishing tool for static websites
License:        MIT
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/App-Dapper/
Source0:        http://www.cpan.org/modules/by-module/App/App-Dapper-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008000
BuildRequires:  perl(CGI)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(DateTime)
BuildRequires:  perl(DateTime::Format::XSD)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Monitor)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(Getopt::Mixed)
BuildRequires:  perl(HTTP::Server::Brick)
BuildRequires:  perl(JSON)
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(Template::Alloy)
BuildRequires:  perl(Template::Constants)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::Markdown)
BuildRequires:  perl(Text::MultiMarkdown)
BuildRequires:  perl(YAML::Tiny)
Requires:       perl(CGI)
Requires:       perl(Data::Dumper)
Requires:       perl(DateTime)
Requires:       perl(DateTime::Format::XSD)
Requires:       perl(Exporter)
Requires:       perl(ExtUtils::MakeMaker)
Requires:       perl(File::Monitor)
Requires:       perl(File::Path)
Requires:       perl(File::Spec::Functions)
Requires:       perl(Getopt::Mixed)
Requires:       perl(HTTP::Server::Brick)
Requires:       perl(JSON)
Requires:       perl(Pod::Usage)
Requires:       perl(Template::Alloy)
Requires:       perl(Template::Constants)
Requires:       perl(Test::More)
Requires:       perl(Text::Markdown)
Requires:       perl(Text::MultiMarkdown)
Requires:       perl(YAML::Tiny)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Dapper helps you build static websites. To get you started, you can use the
dapper init command to initialize a directory. After running this command,
the following directory structure will be created:

%prep
%setup -q -n App-Dapper-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/*

%changelog
* Sun May 29 2022 Michael R. Davis <mrdvt92@yahoo.com> 0.18-1
- Specfile autogenerated by cpanspec 1.78.
